import Foundation

struct AlbumDetailsResponse: Codable {
    let album_type: String
    let artists: [ArtistModel]
    let available_markets: [String]
    let external_urls: [String: String]
    let id: String
    let images: [APIImage]
    let label: String
    let name: String
    let release_date: String
    let total_tracks: Int
    let tracks: TracksResponse
}

struct TracksResponse: Codable {
    let items: [AudioTrackModel]
}

/**
{
    "album_type" = album;
    artists =     (
        {
            "external_urls" =             {
                spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
            };
            href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
            id = 1McMsnEElThX1knmY4oliG;
            name = "Olivia Rodrigo";
            type = artist;
            uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
        }
    );
    "available_markets" =     (
        AD,
        AE,
        AG,
        AL,
        AM,
        AO,
        AR,
        AT,
        AU,
        AZ,
        BA,
        BB,
        BD,
        BE,
        BF,
        BG,
        BH,
        BI,
        BJ,
        BN,
        BO,
        BR,
        BS,
        BT,
        BW,
        BY,
        BZ,
        CA,
        CH,
        CI,
        CL,
        CM,
        CO,
        CR,
        CV,
        CW,
        CY,
        CZ,
        DE,
        DJ,
        DK,
        DM,
        DO,
        DZ,
        EC,
        EE,
        EG,
        ES,
        FI,
        FJ,
        FM,
        FR,
        GA,
        GB,
        GD,
        GE,
        GH,
        GM,
        GN,
        GQ,
        GR,
        GT,
        GW,
        GY,
        HK,
        HN,
        HR,
        HT,
        HU,
        ID,
        IE,
        IL,
        IN,
        IS,
        IT,
        JM,
        JO,
        JP,
        KE,
        KG,
        KH,
        KI,
        KM,
        KN,
        KR,
        KW,
        KZ,
        LA,
        LB,
        LC,
        LI,
        LK,
        LR,
        LS,
        LT,
        LU,
        LV,
        MA,
        MC,
        MD,
        ME,
        MG,
        MH,
        MK,
        ML,
        MN,
        MO,
        MR,
        MT,
        MU,
        MV,
        MW,
        MX,
        MY,
        MZ,
        NA,
        NE,
        NG,
        NI,
        NL,
        NO,
        NP,
        NR,
        NZ,
        OM,
        PA,
        PE,
        PG,
        PH,
        PK,
        PL,
        PS,
        PT,
        PW,
        PY,
        QA,
        RO,
        RS,
        RU,
        RW,
        SA,
        SB,
        SC,
        SE,
        SG,
        SI,
        SK,
        SL,
        SM,
        SN,
        SR,
        ST,
        SV,
        SZ,
        TD,
        TG,
        TH,
        TL,
        TN,
        TO,
        TR,
        TT,
        TV,
        TW,
        TZ,
        UA,
        UG,
        US,
        UY,
        UZ,
        VC,
        VN,
        VU,
        WS,
        XK,
        ZA,
        ZM,
        ZW
    );
    copyrights =     (
        {
            text = "\U00a9 2021 Olivia Rodrigo, under exclusive license to Geffen Records";
            type = C;
        },
        {
            text = "\U2117 2021 Olivia Rodrigo, under exclusive license to Geffen Records";
            type = P;
        }
    );
    "external_ids" =     {
        upc = 00602438268900;
    };
    "external_urls" =     {
        spotify = "https://open.spotify.com/album/7bYichzvtYHdjF8HF69dyA";
    };
    genres =     (
    );
    href = "https://api.spotify.com/v1/albums/7bYichzvtYHdjF8HF69dyA";
    id = 7bYichzvtYHdjF8HF69dyA;
    images =     (
    {
    height = 640;
    url = "https://i.scdn.co/image/ab67616d0000b273bdf5ed83a765fd10a97f08f1";
    width = 640;
    },
    {
    height = 300;
    url = "https://i.scdn.co/image/ab67616d00001e02bdf5ed83a765fd10a97f08f1";
    width = 300;
    },
    {
    height = 64;
    url = "https://i.scdn.co/image/ab67616d00004851bdf5ed83a765fd10a97f08f1";
    width = 64;
    }
    );
    label = "Olivia Rodrigo PS";
    name = SOUR;
    popularity = 42;
    "release_date" = "2021-05-21";
    "release_date_precision" = day;
    "total_tracks" = 11;
    tracks =     {
        href = "https://api.spotify.com/v1/albums/7bYichzvtYHdjF8HF69dyA/tracks?offset=0&limit=50";
        items =         (
            {
                artists =                 (
                    {
                        "external_urls" =                         {
                            spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
                        };
                        href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
                        id = 1McMsnEElThX1knmY4oliG;
                        name = "Olivia Rodrigo";
                        type = artist;
                        uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
                    }
                );
                "available_markets" =                 (
                    AD,
                    AE,
                    AG,
                    AL,
                    AM,
                    AO,
                    AR,
                    AT,
                    AU,
                    AZ,
                    BA,
                    BB,
                    BD,
                    BE,
                    BF,
                    BG,
                    BH,
                    BI,
                    BJ,
                    BN,
                    BO,
                    BR,
                    BS,
                    BT,
                    BW,
                    BY,
                    BZ,
                    CA,
                    CH,
                    CI,
                    CL,
                    CM,
                    CO,
                    CR,
                    CV,
                    CW,
                    CY,
                    CZ,
                    DE,
                    DJ,
                    DK,
                    DM,
                    DO,
                    DZ,
                    EC,
                    EE,
                    EG,
                    ES,
                    FI,
                    FJ,
                    FM,
                    FR,
                    GA,
                    GB,
                    GD,
                    GE,
                    GH,
                    GM,
                    GN,
                    GQ,
                    GR,
                    GT,
                    GW,
                    GY,
                    HK,
                    HN,
                    HR,
                    HT,
                    HU,
                    ID,
                    IE,
                    IL,
                    IN,
                    IS,
                    IT,
                    JM,
                    JO,
                    JP,
                    KE,
                    KG,
                    KH,
                    KI,
                    KM,
                    KN,
                    KR,
                    KW,
                    KZ,
                    LA,
                    LB,
                    LC,
                    LI,
                    LK,
                    LR,
                    LS,
                    LT,
                    LU,
                    LV,
                    MA,
                    MC,
                    MD,
                    ME,
                    MG,
                    MH,
                    MK,
                    ML,
                    MN,
                    MO,
                    MR,
                    MT,
                    MU,
                    MV,
                    MW,
                    MX,
                    MY,
                    MZ,
                    NA,
                    NE,
                    NG,
                    NI,
                    NL,
                    NO,
                    NP,
                    NR,
                    NZ,
                    OM,
                    PA,
                    PE,
                    PG,
                    PH,
                    PK,
                    PL,
                    PS,
                    PT,
                    PW,
                    PY,
                    QA,
                    RO,
                    RS,
                    RU,
                    RW,
                    SA,
                    SB,
                    SC,
                    SE,
                    SG,
                    SI,
                    SK,
                    SL,
                    SM,
                    SN,
                    SR,
                    ST,
                    SV,
                    SZ,
                    TD,
                    TG,
                    TH,
                    TL,
                    TN,
                    TO,
                    TR,
                    TT,
                    TV,
                    TW,
                    TZ,
                    UA,
                    UG,
                    US,
                    UY,
                    UZ,
                    VC,
                    VN,
                    VU,
                    WS,
                    XK,
                    ZA,
                    ZM,
                    ZW
                );
                "disc_number" = 1;
                "duration_ms" = 143746;
                explicit = 0;
                "external_urls" =                 {
                    spotify = "https://open.spotify.com/track/3fZVIxJjV4kXYynsz1G5lr";
                };
                href = "https://api.spotify.com/v1/tracks/3fZVIxJjV4kXYynsz1G5lr";
                id = 3fZVIxJjV4kXYynsz1G5lr;
                "is_local" = 0;
                name = brutal;
                "preview_url" = "<null>";
                "track_number" = 1;
                type = track;
                uri = "spotify:track:3fZVIxJjV4kXYynsz1G5lr";
            },
            {
                artists =                 (
                    {
                        "external_urls" =                         {
                            spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
                        };
                        href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
                        id = 1McMsnEElThX1knmY4oliG;
                        name = "Olivia Rodrigo";
                        type = artist;
                        uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
                    }
                );
                "available_markets" =                 (
                    AD,
                    AE,
                    AG,
                    AL,
                    AM,
                    AO,
                    AR,
                    AT,
                    AU,
                    AZ,
                    BA,
                    BB,
                    BD,
                    BE,
                    BF,
                    BG,
                    BH,
                    BI,
                    BJ,
                    BN,
                    BO,
                    BR,
                    BS,
                    BT,
                    BW,
                    BY,
                    BZ,
                    CA,
                    CH,
                    CI,
                    CL,
                    CM,
                    CO,
                    CR,
                    CV,
                    CW,
                    CY,
                    CZ,
                    DE,
                    DJ,
                    DK,
                    DM,
                    DO,
                    DZ,
                    EC,
                    EE,
                    EG,
                    ES,
                    FI,
                    FJ,
                    FM,
                    FR,
                    GA,
                    GB,
                    GD,
                    GE,
                    GH,
                    GM,
                    GN,
                    GQ,
                    GR,
                    GT,
                    GW,
                    GY,
                    HK,
                    HN,
                    HR,
                    HT,
                    HU,
                    ID,
                    IE,
                    IL,
                    IN,
                    IS,
                    IT,
                    JM,
                    JO,
                    JP,
                    KE,
                    KG,
                    KH,
                    KI,
                    KM,
                    KN,
                    KR,
                    KW,
                    KZ,
                    LA,
                    LB,
                    LC,
                    LI,
                    LK,
                    LR,
                    LS,
                    LT,
                    LU,
                    LV,
                    MA,
                    MC,
                    MD,
                    ME,
                    MG,
                    MH,
                    MK,
                    ML,
                    MN,
                    MO,
                    MR,
                    MT,
                    MU,
                    MV,
                    MW,
                    MX,
                    MY,
                    MZ,
                    NA,
                    NE,
                    NG,
                    NI,
                    NL,
                    NO,
                    NP,
                    NR,
                    NZ,
                    OM,
                    PA,
                    PE,
                    PG,
                    PH,
                    PK,
                    PL,
                    PS,
                    PT,
                    PW,
                    PY,
                    QA,
                    RO,
                    RS,
                    RU,
                    RW,
                    SA,
                    SB,
                    SC,
                    SE,
                    SG,
                    SI,
                    SK,
                    SL,
                    SM,
                    SN,
                    SR,
                    ST,
                    SV,
                    SZ,
                    TD,
                    TG,
                    TH,
                    TL,
                    TN,
                    TO,
                    TR,
                    TT,
                    TV,
                    TW,
                    TZ,
                    UA,
                    UG,
                    US,
                    UY,
                    UZ,
                    VC,
                    VN,
                    VU,
                    WS,
                    XK,
                    ZA,
                    ZM,
                    ZW
                );
                "disc_number" = 1;
                "duration_ms" = 229226;
                explicit = 0;
                "external_urls" =                 {
                    spotify = "https://open.spotify.com/track/6F9U58EHsIPgvQs5eb8O2J";
                };
                href = "https://api.spotify.com/v1/tracks/6F9U58EHsIPgvQs5eb8O2J";
                id = 6F9U58EHsIPgvQs5eb8O2J;
                "is_local" = 0;
                name = traitor;
                "preview_url" = "<null>";
                "track_number" = 2;
                type = track;
                uri = "spotify:track:6F9U58EHsIPgvQs5eb8O2J";
            },
            {
                artists =                 (
                    {
                        "external_urls" =                         {
                            spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
                        };
                        href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
                        id = 1McMsnEElThX1knmY4oliG;
                        name = "Olivia Rodrigo";
                        type = artist;
                        uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
                    }
                );
                "available_markets" =                 (
                    AD,
                    AE,
                    AG,
                    AL,
                    AM,
                    AO,
                    AR,
                    AT,
                    AU,
                    AZ,
                    BA,
                    BB,
                    BD,
                    BE,
                    BF,
                    BG,
                    BH,
                    BI,
                    BJ,
                    BN,
                    BO,
                    BR,
                    BS,
                    BT,
                    BW,
                    BY,
                    BZ,
                    CA,
                    CH,
                    CI,
                    CL,
                    CM,
                    CO,
                    CR,
                    CV,
                    CW,
                    CY,
                    CZ,
                    DE,
                    DJ,
                    DK,
                    DM,
                    DO,
                    DZ,
                    EC,
                    EE,
                    EG,
                    ES,
                    FI,
                    FJ,
                    FM,
                    FR,
                    GA,
                    GB,
                    GD,
                    GE,
                    GH,
                    GM,
                    GN,
                    GQ,
                    GR,
                    GT,
                    GW,
                    GY,
                    HK,
                    HN,
                    HR,
                    HT,
                    HU,
                    ID,
                    IE,
                    IL,
                    IN,
                    IS,
                    IT,
                    JM,
                    JO,
                    JP,
                    KE,
                    KG,
                    KH,
                    KI,
                    KM,
                    KN,
                    KR,
                    KW,
                    KZ,
                    LA,
                    LB,
                    LC,
                    LI,
                    LK,
                    LR,
                    LS,
                    LT,
                    LU,
                    LV,
                    MA,
                    MC,
                    MD,
                    ME,
                    MG,
                    MH,
                    MK,
                    ML,
                    MN,
                    MO,
                    MR,
                    MT,
                    MU,
                    MV,
                    MW,
                    MX,
                    MY,
                    MZ,
                    NA,
                    NE,
                    NG,
                    NI,
                    NL,
                    NO,
                    NP,
                    NR,
                    NZ,
                    OM,
                    PA,
                    PE,
                    PG,
                    PH,
                    PK,
                    PL,
                    PS,
                    PT,
                    PW,
                    PY,
                    QA,
                    RO,
                    RS,
                    RU,
                    RW,
                    SA,
                    SB,
                    SC,
                    SE,
                    SG,
                    SI,
                    SK,
                    SL,
                    SM,
                    SN,
                    SR,
                    ST,
                    SV,
                    SZ,
                    TD,
                    TG,
                    TH,
                    TL,
                    TN,
                    TO,
                    TR,
                    TT,
                    TV,
                    TW,
                    TZ,
                    UA,
                    UG,
                    US,
                    UY,
                    UZ,
                    VC,
                    VN,
                    VU,
                    WS,
                    XK,
                    ZA,
                    ZM,
                    ZW
                );
                "disc_number" = 1;
                "duration_ms" = 242013;
                explicit = 0;
                "external_urls" =                 {
                    spotify = "https://open.spotify.com/track/4ml4WlnHDEpOK8HRVYTCWf";
                };
                href = "https://api.spotify.com/v1/tracks/4ml4WlnHDEpOK8HRVYTCWf";
                id = 4ml4WlnHDEpOK8HRVYTCWf;
                "is_local" = 0;
                name = "drivers license";
                "preview_url" = "<null>";
                "track_number" = 3;
                type = track;
                uri = "spotify:track:4ml4WlnHDEpOK8HRVYTCWf";
            },
            {
                artists =                 (
                    {
                        "external_urls" =                         {
                            spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
                        };
                        href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
                        id = 1McMsnEElThX1knmY4oliG;
                        name = "Olivia Rodrigo";
                        type = artist;
                        uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
                    }
                );
                "available_markets" =                 (
                    AD,
                    AE,
                    AG,
                    AL,
                    AM,
                    AO,
                    AR,
                    AT,
                    AU,
                    AZ,
                    BA,
                    BB,
                    BD,
                    BE,
                    BF,
                    BG,
                    BH,
                    BI,
                    BJ,
                    BN,
                    BO,
                    BR,
                    BS,
                    BT,
                    BW,
                    BY,
                    BZ,
                    CA,
                    CH,
                    CI,
                    CL,
                    CM,
                    CO,
                    CR,
                    CV,
                    CW,
                    CY,
                    CZ,
                    DE,
                    DJ,
                    DK,
                    DM,
                    DO,
                    DZ,
                    EC,
                    EE,
                    EG,
                    ES,
                    FI,
                    FJ,
                    FM,
                    FR,
                    GA,
                    GB,
                    GD,
                    GE,
                    GH,
                    GM,
                    GN,
                    GQ,
                    GR,
                    GT,
                    GW,
                    GY,
                    HK,
                    HN,
                    HR,
                    HT,
                    HU,
                    ID,
                    IE,
                    IL,
                    IN,
                    IS,
                    IT,
                    JM,
                    JO,
                    JP,
                    KE,
                    KG,
                    KH,
                    KI,
                    KM,
                    KN,
                    KR,
                    KW,
                    KZ,
                    LA,
                    LB,
                    LC,
                    LI,
                    LK,
                    LR,
                    LS,
                    LT,
                    LU,
                    LV,
                    MA,
                    MC,
                    MD,
                    ME,
                    MG,
                    MH,
                    MK,
                    ML,
                    MN,
                    MO,
                    MR,
                    MT,
                    MU,
                    MV,
                    MW,
                    MX,
                    MY,
                    MZ,
                    NA,
                    NE,
                    NG,
                    NI,
                    NL,
                    NO,
                    NP,
                    NR,
                    NZ,
                    OM,
                    PA,
                    PE,
                    PG,
                    PH,
                    PK,
                    PL,
                    PS,
                    PT,
                    PW,
                    PY,
                    QA,
                    RO,
                    RS,
                    RU,
                    RW,
                    SA,
                    SB,
                    SC,
                    SE,
                    SG,
                    SI,
                    SK,
                    SL,
                    SM,
                    SN,
                    SR,
                    ST,
                    SV,
                    SZ,
                    TD,
                    TG,
                    TH,
                    TL,
                    TN,
                    TO,
                    TR,
                    TT,
                    TV,
                    TW,
                    TZ,
                    UA,
                    UG,
                    US,
                    UY,
                    UZ,
                    VC,
                    VN,
                    VU,
                    WS,
                    XK,
                    ZA,
                    ZM,
                    ZW
                );
                "disc_number" = 1;
                "duration_ms" = 163586;
                explicit = 0;
                "external_urls" =                 {
                    spotify = "https://open.spotify.com/track/4agPFCccTh7gIho2sNhsJp";
                };
                href = "https://api.spotify.com/v1/tracks/4agPFCccTh7gIho2sNhsJp";
                id = 4agPFCccTh7gIho2sNhsJp;
                "is_local" = 0;
                name = "1 step forward, 3 steps back";
                "preview_url" = "<null>";
                "track_number" = 4;
                type = track;
                uri = "spotify:track:4agPFCccTh7gIho2sNhsJp";
            },
            {
                artists =                 (
                    {
                        "external_urls" =                         {
                            spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
                        };
                        href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
                        id = 1McMsnEElThX1knmY4oliG;
                        name = "Olivia Rodrigo";
                        type = artist;
                        uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
                    }
                );
                "available_markets" =                 (
                    AD,
                    AE,
                    AG,
                    AL,
                    AM,
                    AO,
                    AR,
                    AT,
                    AU,
                    AZ,
                    BA,
                    BB,
                    BD,
                    BE,
                    BF,
                    BG,
                    BH,
                    BI,
                    BJ,
                    BN,
                    BO,
                    BR,
                    BS,
                    BT,
                    BW,
                    BY,
                    BZ,
                    CA,
                    CH,
                    CI,
                    CL,
                    CM,
                    CO,
                    CR,
                    CV,
                    CW,
                    CY,
                    CZ,
                    DE,
                    DJ,
                    DK,
                    DM,
                    DO,
                    DZ,
                    EC,
                    EE,
                    EG,
                    ES,
                    FI,
                    FJ,
                    FM,
                    FR,
                    GA,
                    GB,
                    GD,
                    GE,
                    GH,
                    GM,
                    GN,
                    GQ,
                    GR,
                    GT,
                    GW,
                    GY,
                    HK,
                    HN,
                    HR,
                    HT,
                    HU,
                    ID,
                    IE,
                    IL,
                    IN,
                    IS,
                    IT,
                    JM,
                    JO,
                    JP,
                    KE,
                    KG,
                    KH,
                    KI,
                    KM,
                    KN,
                    KR,
                    KW,
                    KZ,
                    LA,
                    LB,
                    LC,
                    LI,
                    LK,
                    LR,
                    LS,
                    LT,
                    LU,
                    LV,
                    MA,
                    MC,
                    MD,
                    ME,
                    MG,
                    MH,
                    MK,
                    ML,
                    MN,
                    MO,
                    MR,
                    MT,
                    MU,
                    MV,
                    MW,
                    MX,
                    MY,
                    MZ,
                    NA,
                    NE,
                    NG,
                    NI,
                    NL,
                    NO,
                    NP,
                    NR,
                    NZ,
                    OM,
                    PA,
                    PE,
                    PG,
                    PH,
                    PK,
                    PL,
                    PS,
                    PT,
                    PW,
                    PY,
                    QA,
                    RO,
                    RS,
                    RU,
                    RW,
                    SA,
                    SB,
                    SC,
                    SE,
                    SG,
                    SI,
                    SK,
                    SL,
                    SM,
                    SN,
                    SR,
                    ST,
                    SV,
                    SZ,
                    TD,
                    TG,
                    TH,
                    TL,
                    TN,
                    TO,
                    TR,
                    TT,
                    TV,
                    TW,
                    TZ,
                    UA,
                    UG,
                    US,
                    UY,
                    UZ,
                    VC,
                    VN,
                    VU,
                    WS,
                    XK,
                    ZA,
                    ZM,
                    ZW
                );
                "disc_number" = 1;
                "duration_ms" = 215506;
                explicit = 0;
                "external_urls" =                 {
                    spotify = "https://open.spotify.com/track/3ucQ4DLpH8RgyzqYBMnDpj";
                };
                href = "https://api.spotify.com/v1/tracks/3ucQ4DLpH8RgyzqYBMnDpj";
                id = 3ucQ4DLpH8RgyzqYBMnDpj;
                "is_local" = 0;
                name = "deja vu";
                "preview_url" = "<null>";
                "track_number" = 5;
                type = track;
                uri = "spotify:track:3ucQ4DLpH8RgyzqYBMnDpj";
            },
            {
                artists =                 (
                    {
                        "external_urls" =                         {
                            spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
                        };
                        href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
                        id = 1McMsnEElThX1knmY4oliG;
                        name = "Olivia Rodrigo";
                        type = artist;
                        uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
                    }
                );
                "available_markets" =                 (
                    AD,
                    AE,
                    AG,
                    AL,
                    AM,
                    AO,
                    AR,
                    AT,
                    AU,
                    AZ,
                    BA,
                    BB,
                    BD,
                    BE,
                    BF,
                    BG,
                    BH,
                    BI,
                    BJ,
                    BN,
                    BO,
                    BR,
                    BS,
                    BT,
                    BW,
                    BY,
                    BZ,
                    CA,
                    CH,
                    CI,
                    CL,
                    CM,
                    CO,
                    CR,
                    CV,
                    CW,
                    CY,
                    CZ,
                    DE,
                    DJ,
                    DK,
                    DM,
                    DO,
                    DZ,
                    EC,
                    EE,
                    EG,
                    ES,
                    FI,
                    FJ,
                    FM,
                    FR,
                    GA,
                    GB,
                    GD,
                    GE,
                    GH,
                    GM,
                    GN,
                    GQ,
                    GR,
                    GT,
                    GW,
                    GY,
                    HK,
                    HN,
                    HR,
                    HT,
                    HU,
                    ID,
                    IE,
                    IL,
                    IN,
                    IS,
                    IT,
                    JM,
                    JO,
                    JP,
                    KE,
                    KG,
                    KH,
                    KI,
                    KM,
                    KN,
                    KR,
                    KW,
                    KZ,
                    LA,
                    LB,
                    LC,
                    LI,
                    LK,
                    LR,
                    LS,
                    LT,
                    LU,
                    LV,
                    MA,
                    MC,
                    MD,
                    ME,
                    MG,
                    MH,
                    MK,
                    ML,
                    MN,
                    MO,
                    MR,
                    MT,
                    MU,
                    MV,
                    MW,
                    MX,
                    MY,
                    MZ,
                    NA,
                    NE,
                    NG,
                    NI,
                    NL,
                    NO,
                    NP,
                    NR,
                    NZ,
                    OM,
                    PA,
                    PE,
                    PG,
                    PH,
                    PK,
                    PL,
                    PS,
                    PT,
                    PW,
                    PY,
                    QA,
                    RO,
                    RS,
                    RU,
                    RW,
                    SA,
                    SB,
                    SC,
                    SE,
                    SG,
                    SI,
                    SK,
                    SL,
                    SM,
                    SN,
                    SR,
                    ST,
                    SV,
                    SZ,
                    TD,
                    TG,
                    TH,
                    TL,
                    TN,
                    TO,
                    TR,
                    TT,
                    TV,
                    TW,
                    TZ,
                    UA,
                    UG,
                    US,
                    UY,
                    UZ,
                    VC,
                    VN,
                    VU,
                    WS,
                    XK,
                    ZA,
                    ZM,
                    ZW
                );
                "disc_number" = 1;
                "duration_ms" = 178146;
                explicit = 0;
                "external_urls" =                 {
                    spotify = "https://open.spotify.com/track/6P4d1NWBCNIYZjzF9k1mVN";
                };
                href = "https://api.spotify.com/v1/tracks/6P4d1NWBCNIYZjzF9k1mVN";
                id = 6P4d1NWBCNIYZjzF9k1mVN;
                "is_local" = 0;
                name = "good 4 u";
                "preview_url" = "<null>";
                "track_number" = 6;
                type = track;
                uri = "spotify:track:6P4d1NWBCNIYZjzF9k1mVN";
            },
            {
                artists =                 (
                    {
                        "external_urls" =                         {
                            spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
                        };
                        href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
                        id = 1McMsnEElThX1knmY4oliG;
                        name = "Olivia Rodrigo";
                        type = artist;
                        uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
                    }
                );
                "available_markets" =                 (
                    AD,
                    AE,
                    AG,
                    AL,
                    AM,
                    AO,
                    AR,
                    AT,
                    AU,
                    AZ,
                    BA,
                    BB,
                    BD,
                    BE,
                    BF,
                    BG,
                    BH,
                    BI,
                    BJ,
                    BN,
                    BO,
                    BR,
                    BS,
                    BT,
                    BW,
                    BY,
                    BZ,
                    CA,
                    CH,
                    CI,
                    CL,
                    CM,
                    CO,
                    CR,
                    CV,
                    CW,
                    CY,
                    CZ,
                    DE,
                    DJ,
                    DK,
                    DM,
                    DO,
                    DZ,
                    EC,
                    EE,
                    EG,
                    ES,
                    FI,
                    FJ,
                    FM,
                    FR,
                    GA,
                    GB,
                    GD,
                    GE,
                    GH,
                    GM,
                    GN,
                    GQ,
                    GR,
                    GT,
                    GW,
                    GY,
                    HK,
                    HN,
                    HR,
                    HT,
                    HU,
                    ID,
                    IE,
                    IL,
                    IN,
                    IS,
                    IT,
                    JM,
                    JO,
                    JP,
                    KE,
                    KG,
                    KH,
                    KI,
                    KM,
                    KN,
                    KR,
                    KW,
                    KZ,
                    LA,
                    LB,
                    LC,
                    LI,
                    LK,
                    LR,
                    LS,
                    LT,
                    LU,
                    LV,
                    MA,
                    MC,
                    MD,
                    ME,
                    MG,
                    MH,
                    MK,
                    ML,
                    MN,
                    MO,
                    MR,
                    MT,
                    MU,
                    MV,
                    MW,
                    MX,
                    MY,
                    MZ,
                    NA,
                    NE,
                    NG,
                    NI,
                    NL,
                    NO,
                    NP,
                    NR,
                    NZ,
                    OM,
                    PA,
                    PE,
                    PG,
                    PH,
                    PK,
                    PL,
                    PS,
                    PT,
                    PW,
                    PY,
                    QA,
                    RO,
                    RS,
                    RU,
                    RW,
                    SA,
                    SB,
                    SC,
                    SE,
                    SG,
                    SI,
                    SK,
                    SL,
                    SM,
                    SN,
                    SR,
                    ST,
                    SV,
                    SZ,
                    TD,
                    TG,
                    TH,
                    TL,
                    TN,
                    TO,
                    TR,
                    TT,
                    TV,
                    TW,
                    TZ,
                    UA,
                    UG,
                    US,
                    UY,
                    UZ,
                    VC,
                    VN,
                    VU,
                    WS,
                    XK,
                    ZA,
                    ZM,
                    ZW
                );
                "disc_number" = 1;
                "duration_ms" = 202826;
                explicit = 0;
                "external_urls" =                 {
                    spotify = "https://open.spotify.com/track/3T8KVPcFVyyzswMnS8NC8t";
                };
                href = "https://api.spotify.com/v1/tracks/3T8KVPcFVyyzswMnS8NC8t";
                id = 3T8KVPcFVyyzswMnS8NC8t;
                "is_local" = 0;
                name = "enough for you";
                "preview_url" = "<null>";
                "track_number" = 7;
                type = track;
                uri = "spotify:track:3T8KVPcFVyyzswMnS8NC8t";
            },
            {
                artists =                 (
                    {
                        "external_urls" =                         {
                            spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
                        };
                        href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
                        id = 1McMsnEElThX1knmY4oliG;
                        name = "Olivia Rodrigo";
                        type = artist;
                        uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
                    }
                );
                "available_markets" =                 (
                    AD,
                    AE,
                    AG,
                    AL,
                    AM,
                    AO,
                    AR,
                    AT,
                    AU,
                    AZ,
                    BA,
                    BB,
                    BD,
                    BE,
                    BF,
                    BG,
                    BH,
                    BI,
                    BJ,
                    BN,
                    BO,
                    BR,
                    BS,
                    BT,
                    BW,
                    BY,
                    BZ,
                    CA,
                    CH,
                    CI,
                    CL,
                    CM,
                    CO,
                    CR,
                    CV,
                    CW,
                    CY,
                    CZ,
                    DE,
                    DJ,
                    DK,
                    DM,
                    DO,
                    DZ,
                    EC,
                    EE,
                    EG,
                    ES,
                    FI,
                    FJ,
                    FM,
                    FR,
                    GA,
                    GB,
                    GD,
                    GE,
                    GH,
                    GM,
                    GN,
                    GQ,
                    GR,
                    GT,
                    GW,
                    GY,
                    HK,
                    HN,
                    HR,
                    HT,
                    HU,
                    ID,
                    IE,
                    IL,
                    IN,
                    IS,
                    IT,
                    JM,
                    JO,
                    JP,
                    KE,
                    KG,
                    KH,
                    KI,
                    KM,
                    KN,
                    KR,
                    KW,
                    KZ,
                    LA,
                    LB,
                    LC,
                    LI,
                    LK,
                    LR,
                    LS,
                    LT,
                    LU,
                    LV,
                    MA,
                    MC,
                    MD,
                    ME,
                    MG,
                    MH,
                    MK,
                    ML,
                    MN,
                    MO,
                    MR,
                    MT,
                    MU,
                    MV,
                    MW,
                    MX,
                    MY,
                    MZ,
                    NA,
                    NE,
                    NG,
                    NI,
                    NL,
                    NO,
                    NP,
                    NR,
                    NZ,
                    OM,
                    PA,
                    PE,
                    PG,
                    PH,
                    PK,
                    PL,
                    PS,
                    PT,
                    PW,
                    PY,
                    QA,
                    RO,
                    RS,
                    RU,
                    RW,
                    SA,
                    SB,
                    SC,
                    SE,
                    SG,
                    SI,
                    SK,
                    SL,
                    SM,
                    SN,
                    SR,
                    ST,
                    SV,
                    SZ,
                    TD,
                    TG,
                    TH,
                    TL,
                    TN,
                    TO,
                    TR,
                    TT,
                    TV,
                    TW,
                    TZ,
                    UA,
                    UG,
                    US,
                    UY,
                    UZ,
                    VC,
                    VN,
                    VU,
                    WS,
                    XK,
                    ZA,
                    ZM,
                    ZW
                );
                "disc_number" = 1;
                "duration_ms" = 175933;
                explicit = 0;
                "external_urls" =                 {
                    spotify = "https://open.spotify.com/track/3JJneCSDh1685L9OVvTiIo";
                };
                href = "https://api.spotify.com/v1/tracks/3JJneCSDh1685L9OVvTiIo";
                id = 3JJneCSDh1685L9OVvTiIo;
                "is_local" = 0;
                name = happier;
                "preview_url" = "<null>";
                "track_number" = 8;
                type = track;
                uri = "spotify:track:3JJneCSDh1685L9OVvTiIo";
            },
            {
                artists =                 (
                    {
                        "external_urls" =                         {
                            spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
                        };
                        href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
                        id = 1McMsnEElThX1knmY4oliG;
                        name = "Olivia Rodrigo";
                        type = artist;
                        uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
                    }
                );
                "available_markets" =                 (
                    AD,
                    AE,
                    AG,
                    AL,
                    AM,
                    AO,
                    AR,
                    AT,
                    AU,
                    AZ,
                    BA,
                    BB,
                    BD,
                    BE,
                    BF,
                    BG,
                    BH,
                    BI,
                    BJ,
                    BN,
                    BO,
                    BR,
                    BS,
                    BT,
                    BW,
                    BY,
                    BZ,
                    CA,
                    CH,
                    CI,
                    CL,
                    CM,
                    CO,
                    CR,
                    CV,
                    CW,
                    CY,
                    CZ,
                    DE,
                    DJ,
                    DK,
                    DM,
                    DO,
                    DZ,
                    EC,
                    EE,
                    EG,
                    ES,
                    FI,
                    FJ,
                    FM,
                    FR,
                    GA,
                    GB,
                    GD,
                    GE,
                    GH,
                    GM,
                    GN,
                    GQ,
                    GR,
                    GT,
                    GW,
                    GY,
                    HK,
                    HN,
                    HR,
                    HT,
                    HU,
                    ID,
                    IE,
                    IL,
                    IN,
                    IS,
                    IT,
                    JM,
                    JO,
                    JP,
                    KE,
                    KG,
                    KH,
                    KI,
                    KM,
                    KN,
                    KR,
                    KW,
                    KZ,
                    LA,
                    LB,
                    LC,
                    LI,
                    LK,
                    LR,
                    LS,
                    LT,
                    LU,
                    LV,
                    MA,
                    MC,
                    MD,
                    ME,
                    MG,
                    MH,
                    MK,
                    ML,
                    MN,
                    MO,
                    MR,
                    MT,
                    MU,
                    MV,
                    MW,
                    MX,
                    MY,
                    MZ,
                    NA,
                    NE,
                    NG,
                    NI,
                    NL,
                    NO,
                    NP,
                    NR,
                    NZ,
                    OM,
                    PA,
                    PE,
                    PG,
                    PH,
                    PK,
                    PL,
                    PS,
                    PT,
                    PW,
                    PY,
                    QA,
                    RO,
                    RS,
                    RU,
                    RW,
                    SA,
                    SB,
                    SC,
                    SE,
                    SG,
                    SI,
                    SK,
                    SL,
                    SM,
                    SN,
                    SR,
                    ST,
                    SV,
                    SZ,
                    TD,
                    TG,
                    TH,
                    TL,
                    TN,
                    TO,
                    TR,
                    TT,
                    TV,
                    TW,
                    TZ,
                    UA,
                    UG,
                    US,
                    UY,
                    UZ,
                    VC,
                    VN,
                    VU,
                    WS,
                    XK,
                    ZA,
                    ZM,
                    ZW
                );
                "disc_number" = 1;
                "duration_ms" = 173160;
                explicit = 0;
                "external_urls" =                 {
                    spotify = "https://open.spotify.com/track/2dzydxg33Wh5jEtHxhAc60";
                };
                href = "https://api.spotify.com/v1/tracks/2dzydxg33Wh5jEtHxhAc60";
                id = 2dzydxg33Wh5jEtHxhAc60;
                "is_local" = 0;
                name = "jealousy, jealousy";
                "preview_url" = "<null>";
                "track_number" = 9;
                type = track;
                uri = "spotify:track:2dzydxg33Wh5jEtHxhAc60";
            },
            {
                artists =                 (
                    {
                        "external_urls" =                         {
                            spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
                        };
                        href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
                        id = 1McMsnEElThX1knmY4oliG;
                        name = "Olivia Rodrigo";
                        type = artist;
                        uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
                    }
                );
                "available_markets" =                 (
                    AD,
                    AE,
                    AG,
                    AL,
                    AM,
                    AO,
                    AR,
                    AT,
                    AU,
                    AZ,
                    BA,
                    BB,
                    BD,
                    BE,
                    BF,
                    BG,
                    BH,
                    BI,
                    BJ,
                    BN,
                    BO,
                    BR,
                    BS,
                    BT,
                    BW,
                    BY,
                    BZ,
                    CA,
                    CH,
                    CI,
                    CL,
                    CM,
                    CO,
                    CR,
                    CV,
                    CW,
                    CY,
                    CZ,
                    DE,
                    DJ,
                    DK,
                    DM,
                    DO,
                    DZ,
                    EC,
                    EE,
                    EG,
                    ES,
                    FI,
                    FJ,
                    FM,
                    FR,
                    GA,
                    GB,
                    GD,
                    GE,
                    GH,
                    GM,
                    GN,
                    GQ,
                    GR,
                    GT,
                    GW,
                    GY,
                    HK,
                    HN,
                    HR,
                    HT,
                    HU,
                    ID,
                    IE,
                    IL,
                    IN,
                    IS,
                    IT,
                    JM,
                    JO,
                    JP,
                    KE,
                    KG,
                    KH,
                    KI,
                    KM,
                    KN,
                    KR,
                    KW,
                    KZ,
                    LA,
                    LB,
                    LC,
                    LI,
                    LK,
                    LR,
                    LS,
                    LT,
                    LU,
                    LV,
                    MA,
                    MC,
                    MD,
                    ME,
                    MG,
                    MH,
                    MK,
                    ML,
                    MN,
                    MO,
                    MR,
                    MT,
                    MU,
                    MV,
                    MW,
                    MX,
                    MY,
                    MZ,
                    NA,
                    NE,
                    NG,
                    NI,
                    NL,
                    NO,
                    NP,
                    NR,
                    NZ,
                    OM,
                    PA,
                    PE,
                    PG,
                    PH,
                    PK,
                    PL,
                    PS,
                    PT,
                    PW,
                    PY,
                    QA,
                    RO,
                    RS,
                    RU,
                    RW,
                    SA,
                    SB,
                    SC,
                    SE,
                    SG,
                    SI,
                    SK,
                    SL,
                    SM,
                    SN,
                    SR,
                    ST,
                    SV,
                    SZ,
                    TD,
                    TG,
                    TH,
                    TL,
                    TN,
                    TO,
                    TR,
                    TT,
                    TV,
                    TW,
                    TZ,
                    UA,
                    UG,
                    US,
                    UY,
                    UZ,
                    VC,
                    VN,
                    VU,
                    WS,
                    XK,
                    ZA,
                    ZM,
                    ZW
                );
                "disc_number" = 1;
                "duration_ms" = 152666;
                explicit = 0;
                "external_urls" =                 {
                    spotify = "https://open.spotify.com/track/61W7tEpxEfmizp6V5ZRN10";
                };
                href = "https://api.spotify.com/v1/tracks/61W7tEpxEfmizp6V5ZRN10";
                id = 61W7tEpxEfmizp6V5ZRN10;
                "is_local" = 0;
                name = "favorite crime";
                "preview_url" = "<null>";
                "track_number" = 10;
                type = track;
                uri = "spotify:track:61W7tEpxEfmizp6V5ZRN10";
            },
            {
                artists =                 (
                    {
                        "external_urls" =                         {
                            spotify = "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG";
                        };
                        href = "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG";
                        id = 1McMsnEElThX1knmY4oliG;
                        name = "Olivia Rodrigo";
                        type = artist;
                        uri = "spotify:artist:1McMsnEElThX1knmY4oliG";
                    }
                );
                "available_markets" =                 (
                    AD,
                    AE,
                    AG,
                    AL,
                    AM,
                    AO,
                    AR,
                    AT,
                    AU,
                    AZ,
                    BA,
                    BB,
                    BD,
                    BE,
                    BF,
                    BG,
                    BH,
                    BI,
                    BJ,
                    BN,
                    BO,
                    BR,
                    BS,
                    BT,
                    BW,
                    BY,
                    BZ,
                    CA,
                    CH,
                    CI,
                    CL,
                    CM,
                    CO,
                    CR,
                    CV,
                    CW,
                    CY,
                    CZ,
                    DE,
                    DJ,
                    DK,
                    DM,
                    DO,
                    DZ,
                    EC,
                    EE,
                    EG,
                    ES,
                    FI,
                    FJ,
                    FM,
                    FR,
                    GA,
                    GB,
                    GD,
                    GE,
                    GH,
                    GM,
                    GN,
                    GQ,
                    GR,
                    GT,
                    GW,
                    GY,
                    HK,
                    HN,
                    HR,
                    HT,
                    HU,
                    ID,
                    IE,
                    IL,
                    IN,
                    IS,
                    IT,
                    JM,
                    JO,
                    JP,
                    KE,
                    KG,
                    KH,
                    KI,
                    KM,
                    KN,
                    KR,
                    KW,
                    KZ,
                    LA,
                    LB,
                    LC,
                    LI,
                    LK,
                    LR,
                    LS,
                    LT,
                    LU,
                    LV,
                    MA,
                    MC,
                    MD,
                    ME,
                    MG,
                    MH,
                    MK,
                    ML,
                    MN,
                    MO,
                    MR,
                    MT,
                    MU,
                    MV,
                    MW,
                    MX,
                    MY,
                    MZ,
                    NA,
                    NE,
                    NG,
                    NI,
                    NL,
                    NO,
                    NP,
                    NR,
                    NZ,
                    OM,
                    PA,
                    PE,
                    PG,
                    PH,
                    PK,
                    PL,
                    PS,
                    PT,
                    PW,
                    PY,
                    QA,
                    RO,
                    RS,
                    RU,
                    RW,
                    SA,
                    SB,
                    SC,
                    SE,
                    SG,
                    SI,
                    SK,
                    SL,
                    SM,
                    SN,
                    SR,
                    ST,
                    SV,
                    SZ,
                    TD,
                    TG,
                    TH,
                    TL,
                    TN,
                    TO,
                    TR,
                    TT,
                    TV,
                    TW,
                    TZ,
                    UA,
                    UG,
                    US,
                    UY,
                    UZ,
                    VC,
                    VN,
                    VU,
                    WS,
                    XK,
                    ZA,
                    ZM,
                    ZW
                );
                "disc_number" = 1;
                "duration_ms" = 209560;
                explicit = 0;
                "external_urls" =                 {
                    spotify = "https://open.spotify.com/track/1QnqdRLbL6yxHFirIokIMg";
                };
                href = "https://api.spotify.com/v1/tracks/1QnqdRLbL6yxHFirIokIMg";
                id = 1QnqdRLbL6yxHFirIokIMg;
                "is_local" = 0;
                name = "hope ur ok";
                "preview_url" = "<null>";
                "track_number" = 11;
                type = track;
                uri = "spotify:track:1QnqdRLbL6yxHFirIokIMg";
            }
        );
        limit = 50;
        next = "<null>";
        offset = 0;
        previous = "<null>";
        total = 11;
    };
    type = album;
    uri = "spotify:album:7bYichzvtYHdjF8HF69dyA";
}
*/
